variables:
  work_dir: /home/jovyan/zoloev-city/gigachat
  run_name: llama_from_layer_slice_1
  model_name: meta-llama/Llama-3.2-3B
  tokenizer_name: ${variables.model_name}
  dataset_name: rosbank
  max_seq_len: 8192
  global_seed: 42

  data_path: ${variables.work_dir}/source/ptls-experiments/scenario_${variables.dataset_name}/data
  data_local: ${variables.data_path}/streaming_${variables.run_name}
  data_remote: 

  embeddings_output_path: ${variables.data_local}/embeddings_${variables.run_name}.parquet

  text_convertation:
   use_augmentation: true
   out_file: ${variables.data_path}/transactions_text_marked.jsonl

  streaming_convertation:
    path: ${variables.text_convertation.out_file}
    out_root: ${variables.data_local}
    split: train
    tokenizer: ${variables.model_name}
    concat_tokens: 8192
    compression: zstd
    eos_text: <|endoftext|>
    bos_text: 
    no_wrap: true

  model_convertation:
    composer_path: ${variables.work_dir}/checkpoints/${variables.dataset_name}/${variables.run_name}/latest-rank0.pt
    hf_output_path: ${variables.work_dir}/checkpoints/${variables.dataset_name}/${variables.run_name}/hf_format
    output_precision: bf16
    local_checkpoint_save_location: null
    hf_repo_for_upload: null
    test_uploaded_model: false
    trust_remote_code: true

  dataset:
    train_path: ${variables.data_path}/train_trx.parquet
    test_path: ${variables.data_path}/test_trx.parquet

    col_id: "cl_id"
    header_features: 
        - "UNIX days"
        - "Amount(rubles, scaled)"
        - "Merchant category codes"
        - "Channel_type(SWIFT transfer, credit card repayment, or intra-bank transfer and etc)"
        - "Transaction category(ATM withdrawal, purchase in the terminal and etc)"
    header_separator: "|"
    features:
        - "event_time"
        - "amount"
        - "mcc"
        - "channel_type"
        - "trx_category"
    feature_separator: ", "
    trx_separator: "\n"

  inference:
    equal_pad_eos_id: true
    use_bfloat16: true
    from_layer_slice: 27
  

max_seq_len: ${variables.max_seq_len}
run_name: ${variables.run_name}

save_folder: ${variables.work_dir}/checkpoints/${variables.dataset_name}/${run_name}
save_weights_only: true
save_interval: 2ep


model:
  name: hf_causal_lm
  pretrained_model_name_or_path: ${variables.model_name}
  pretrained: true
  use_auth_token: true
  use_flash_attention_2: true

tokenizer:
  name: ${variables.tokenizer_name}
  kwargs:
    model_max_length: ${variables.max_seq_len}

train_loader:
  name: text
  dataset:
    local: ${variables.data_local}
    remote: ${variables.data_remote}
    shuffle: true
    # split: train
    max_seq_len: ${variables.max_seq_len}
    shuffle_seed: ${variables.global_seed}
  pin_memory: true
  prefetch_factor: 2
  persistent_workers: true
  drop_last: true
  num_workers: 8

scheduler:
  name: cosine_with_warmup
  t_warmup: 10ba
  alpha_f: 0.1

optimizer:
  name: decoupled_adamw
  lr: 1.0e-5
  betas:
  - 0.9
  - 0.95
  eps: 1.0e-05
  weight_decay: 1.0e-6

algorithms:
  gradient_clipping:
    clipping_type: norm
    clipping_threshold: 1.0

max_duration: 2ep
eval_interval: 100000ep
eval_first: false

global_train_batch_size: 8
device_train_microbatch_size: 1
device_train_grad_accum: 1

seed: ${variables.global_seed}
precision: amp_bf16
dist_timeout: 6000
expandable_segments: true

fsdp_config:
  mixed_precision: PURE
  state_dict_type: full
  limit_all_gathers: true
  sharding_strategy: FULL_SHARD
  backward_prefetch: BACKWARD_PRE
  activation_cpu_offload: false
  activation_checkpointing: false
  activation_checkpointing_reentrant: false

progress_bar: false
log_to_console: true
console_log_interval: 10ba

loggers:
  wandb: {}

callbacks:
  speed_monitor:
    window_size: 10
  lr_monitor: {}
  memory_monitor: {}
  runtime_estimator: {}
